### PR TITLE
Add more currencies and more examples for the existing intents

### PR DESCRIPTION
**Pull request by jusce17**
I have gathered Natural language inputs from 26 people from 9 different countries, you can see the sample from the file 
[here](https://github.com/RasaHQ/NLU-training-data/files/5318563/Natural.Language.Processing.Research.xlsx). I have also gather some new intents from them but still need to analyze better the data

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @b-quachtran will take a look at it as soon as possible ✨

**Comment by koaning** [comment]
Hi @jusce17 it seems like you also added a `.DS_store` file. This is something Mac related, but could you remove the file? The other additions look good to me :) !

**Comment by jusce17** [comment]
Sure @koaning , doing it right now

**Comment by jusce17** [comment]
Done @koaning

**Review by EmmaWightman — APPROVED** [review]
Looks awesome, thanks @jusce17 !

**Review by EmmaWightman — APPROVED** [review]

**Pull request merged**
