### PR TITLE
add approx 90 different intent

### PR DESCRIPTION
**Pull request by abhishakvarshney**

### CODE REVIEW

**Comment by bhanuSingh97** [comment]
Hi @abhishakvarshney 
Thanks for sharing such a rich nlu file. It would be very nice of you if you would share a list of intents and entities as well.

**Comment by abhishakvarshney** [comment]
Hi @bhanuSingh97 
I am developing Birbal bot as an open source project. I update it regularly on my github. You can fetch whatever data you want from there.

**Comment by EmmaWightman** [comment]
Hey @abhishakvarshney 

Thank you so much for donating all of this training data! 90+ intents is an incredible amount!

Based on evaluating the first contributions, we have decided to make a few updates to the repo README.md and FAQ. 
Apologies for doing this in retrospect, but after discussion we think it would make sense to sooner rather than later. The changes are as follows: **1. remove all entities from the training data and **2. add a short description of each intent.** 

**1. Why did we decide to remove entities?** 
We would like to make the training data as easy as possible to adopt to new training models and annotating entities highly dependant on your bot’s purpose. Therefore, we will first focus on collecting training data that only includes intents.

To help you remove the annotated entities from your training data, you can run [**this script**](https://github.com/RasaHQ/NLU-training-data/blob/master/entity-removal-script) which should make the process straight forward.

**2. Why do I need to add a description to the intents?** 
We think this is great practice to ensure that intents are consistent and clear. 
Like this for example, `intent:can_you_help <!--The user is asking the agent for help.-->` this way the intent is clear for anyone adapting the data.  

Additionally, I think @bhanuSingh97 is referring to updating the readme.md to list the intents included in your folder. :) 

Do you think it would be possible for you to adapt the data to meet these requirements? If you have any questions at all do not hesitate to reach out. 

We appreciate your support! :)

**Comment by EmmaWightman** [comment]
Hey there @abhishakvarshney 

I wanted to give you a friendly reminder: It's been a while since you submitted this PR, there are still some adjustments to be made before we can merge it. 

Would you be able to make those changes? Please let me know if have any questions or concerns.

**Pull request closed without merging**
