### PR TITLE
Buy a car

### PR DESCRIPTION
**Pull request by claudio1975**

### CODE REVIEW

**Comment by EmmaWightman** [comment]
Hey @claudio1975 , 

This is fantastic! Thank you for donating all of this training data! 

Based on evaluating the first contributions, we have decided to make a few updates to the repo README.md and FAQ. 
Apologies for doing this in retrospect, but after discussion we think it would make sense to sooner rather than later. The changes are as follows: **1. remove all entities from the training data and 2. add a short description of each intent.** 

**1. Why did we decide to remove entities?** 
We would like to make the training data as easy as possible to adopt to new training models and annotating entities highly dependant on your bot’s purpose. Therefore, we will first focus on collecting training data that only includes intents.

To help you remove the annotated entities from your training data, you can back up your data and then run [**this script**](https://github.com/RasaHQ/NLU-training-data/blob/master/entity-removal-script) which should make the process straight forward.

**2. Why do I need to add a description to the intents?** 
We think this is great practice to ensure that intents are consistent and clear. 
Like this for example, `intent:locate_car_dealer <!--The user would like to see the closest car dealer .-->` this way the intent is clear for anyone adapting the data.  

Lastly, please remove the `smalltalk` data from the `car` folder. You can instead add this to the `smalltalk` folder [here](https://github.com/RasaHQ/NLU-training-data/tree/master/smalltalk).  

Do you think it would be possible for you to adapt the data to meet these requirements? If you have any questions at all do not hesitate to reach out. 

We appreciate your support! :)

**Comment by claudio1975** [comment]
Sorry I'm new git user and I'm not able to run the script neither using a folder of my local machine (permissione denied) or using the GitHub repository (invalid argument)

**Comment by EmmaWightman** [comment]
Hey @claudio1975,

The descriptions are great!  I see you have removed all intents along with entities, we would really love to keep those intents if possible. 
Could you give us more information on how you're running the script and the errors you're getting? We would really like to support you with this, so feel free to also send any logs that you have too.

**Comment by claudio1975** [comment]
I'd understood to keep only the main intents and not also the training sentences.
I've updated the file.
Automated checks seems to be right, is it ok?

**Pull request merged**
