### PR TITLE
Added currency and some statements for other banking intents.

### PR DESCRIPTION
**Pull request by umangnangal**
Adding @EmmaWightman  for PR.

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @degiz will take a look at it as soon as possible ✨

**Comment by degiz** [comment]
@koaning could you please take a look?

**Comment by koaning** [comment]
@umangnangal could you sign our CLA? Without it we cannot accept a PR on this repository.

**Comment by umangnangal** [comment]
> @umangnangal could you sign our CLA? Without it we cannot accept a PR on this repository.

I signed the CLA but it still it is not showing up here.

**Comment by umangnangal** [comment]
@koaning @degiz  Any update on this?

**Comment by koaning** [comment]
@EmmaWightman I don't have merge priviledges. This looks good to me, could you merge?

**Review by EmmaWightman — APPROVED** [review]

**Pull request merged**
