### PR TITLE
Added data for mood angry and scared

### PR DESCRIPTION
**Pull request by rajsukanya**

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @melindaloubser1 will take a look at it as soon as possible ✨

**Comment by rajsukanya** [comment]
Hi @EmmaWightman,I already signed the CLA but for some reason, it still says I haven't. When I click on the CLA link provided, I get the following attachment picture but when I click the recheck link, it still says I didn't sign the CLA yet. 


 
 
  On Thu, Jun 18, 2020 at 7:28 AM, EmmaWightman<notifications@github.com> wrote:   


@EmmaWightman approved this pull request.

thank you for sharing this data @rajsukanya! Could you sign the CLA so I can merge this one? :)

**Comment by EmmaWightman** [comment]
Hi @rajsukanya 

Sorry to hear you're having trouble with it - I am sure we can find a solution :) I made a few adjustments to the PR - could you let me know if anything has changed and if you're able to submit your signed CLA?

**Comment by rajsukanya** [comment]
The following attachment is my signed CLA. Also, the data I wrote didn't change. 

    On Friday, June 19, 2020, 4:18:06 AM EDT, EmmaWightman <notifications@github.com> wrote:  
 
 


Hi @rajsukanya

Sorry to hear you're having trouble with it - I am sure we can find a solution :) I made a few adjustments to the PR - could you let me know if anything has changed and if you're able to submit your signed CLA?

**Comment by rajsukanya** [comment]
Dear Rasa Admins, 
I'm following up about my pending merge request. Let me know what I can do to facilitate bringing it to fruition.
Thanks,Sukanya

**Comment by EmmaWightman** [comment]
Hi @rajsukanya 

GitHub suggest "rajsukanya seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account."

Could you make sure your email is verified with your github account? :)

**Comment by rajsukanya** [comment]
Hi @EmmaWightman    

Yes, my email is verified with my github account. I then rechecked the status but it still says that the CLA is not signed.

**Pull request merged**
