### PR TITLE
Added restaurant-table-reservation training data

### PR DESCRIPTION
**Pull request by shrey1608**
Training data for user to ask for the restaurants,their types, table preference and giving the restaurant review

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @Ghostvv will take a look at it as soon as possible ✨

**Comment by shrey1608** [comment]
Any updates on merging the PR?

**Comment by koaning** [comment]
I like the additions, thanks @shrey1608. One thing, could you remove the comments? I've noticed some of our documents have them but the intent description and the examples should be enough to explain what the intent is supposed to be used for.

**Comment by shrey1608** [comment]
Thanks for reviewing @koaning . I have updated the PR by removing the comments from it . Do have a look at it and do tell if you need to change anything else.

**Review by koaning — APPROVED** [review]

**Comment by koaning** [comment]
@EmmaWightman can you click the big green merge button :) ?

**Comment by shrey1608** [comment]
@EmmaWightman If everything is good can you merge it?

**Comment by shrey1608** [comment]
can anyone merge the PR?

**Comment by shrey1608** [comment]
Any updates @EmmaWightman ?

**Review by EmmaWightman — APPROVED** [review]

**Comment by EmmaWightman** [comment]
Apologies for the delay @shrey1608 this is awesome, thank you for submitting!

**Pull request merged**
