### PR TITLE
Added employment bot nlu data

### PR DESCRIPTION
**Pull request by azharameen**
added employment nlu data

### CODE REVIEW

**Comment by EmmaWightman** [comment]
Hey @azharameen, 

Thank you for donating all of this training data! 

Based on evaluating the first contributions, we have decided to make a few updates to the repo README.md and FAQ. 
Apologies for doing this in retrospect, but after discussion we think it would make sense to sooner rather than later. The changes are as follows: **1. remove all entities from the training data and 2. add a short description of each intent.** 

**1. Why did we decide to remove entities?** 
We would like to make the training data as easy as possible to adopt to new training models and annotating entities highly dependant on your bot’s purpose. Therefore, we will first focus on collecting training data that only includes intents.

To help you remove the annotated entities from your training data, you can back up your data and then run [**this script**](https://github.com/RasaHQ/NLU-training-data/blob/master/entity-removal-script) which should make the process straight forward.

**2. Why do I need to add a description to the intents?** 
We think this is great practice to ensure that intents are consistent and clear. 
Like this for example, `intent:asked_mother_name <!--The agent is asking for name of the user's mother.-->` this way the intent is clear for anyone adapting the data.  

Lastly, please remove the `smalltalk` data from the `employment` folder. You can instead add this to the `smalltalk` folder [here](https://github.com/RasaHQ/NLU-training-data/tree/master/smalltalk).  

Do you think it would be possible for you to adapt the data to meet these requirements? If you have any questions at all do not hesitate to reach out. 

We appreciate your support! :)

**Comment by azharameen** [comment]
Thanks @EmmaWightman I will update the training data as you said, but how can we train entities if not mentioned in nlu.md. Sorry if I my understanding is not correct. Let me know.
Thanks again for guiding

**Comment by EmmaWightman** [comment]
Hi @azharameen,

Ideally you will be able to train the intents and customize the entities yourself based on your bot's purpose. 

Does this help? Let me know if you need more info on this. :)

**Comment by EmmaWightman** [comment]
Hey there @azharameen 

I wanted to give you a friendly reminder: It's been a while since you submitted this PR, there are still some adjustments to be made before we can merge it. 

Would you be able to make those changes? Please let me know if have any questions or concerns.

**Pull request closed without merging**
